public class Listprogram {

    public static List<String> task31(List<string> country){
        
        country.add('india');
        country.add('us');
        country.add('uk');
        country.add('sri lanka');
        
        List<String> capital=new List<String>();
        capital.add('New Delhi');
        capital.add('New york');
        capital.add('London');
        capital.add('Colombo');
        
        return capital;
    }
}